### ISSUE TITLE
loads "About" page every time i run it

### ISSUE THREAD

**Issue by ghost** [sderaut/obmenux#3] opened 2015-09-10 21:34 UTC
i don't know if there's a config file that has a "runOnce" option that's not being flagged because it's not actually being installed to my system via an arch package, but...

either way, it would be nice if that just never happened.

**Comment by sderaut** [comment] 2015-09-10 22:07
I get the same thing, ever since I changed the "About" page at all from the original.

Issue confirmed and expected to be open for a while until other things about the set up are improved.

**Comment by sderaut** [comment] 2015-09-10 23:48
Fixed by commit 93eab5e2b2a769f132d77f67fe4623c1e4c1b20e

It was one of the changes in the Debian patches, an obvious one word True to False change. It hadn't been applied yet because before this I was only using the Debian patches via copying the Ubuntu version of the files obmenu and obxml.py before making my own drastic changes to those files (which I also renamed to 'obmenux' and 'obxmlx.py'.)

Closing this issue.

**Closed as completed by sderaut** 2015-09-10 23:48 UTC

**Comment by keithbowes** [comment] 2020-03-03 14:53
This "fix" was also my first thought in [my fork of obmenu](https://github.com/keithbowes/obmenu), but it revealed a bug of its own: the about dialog would only show once and if you tried to show it again, only a blank gray box would show (with GTK assertions on stderr).  What I ultimately did was moved the about dialog to a separate glade file.
